services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3011:80"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"